nav:
  Home: /
  Résumé: /resume/
  Hire Me: http://github.com/probberechts

customize:
  gravatar:
    email: 123.sourav@gmail.com
  logo:
    enabled: true
    width: 64
    height: 64
    url: /images/logo.png
    gravatar: true
  favicon: 
    # eg. generate with http://realfavicongenerator.net/
  desktop:
    url: /images/favicon.ico
    gravatar: true
  android:
    url: /images/favicon-192x192.png
    gravator: true
  apple:
    url: /images/apple-touch-icon.png
    gravator: true
  social_links:
    github: http://github.com/souravray
    product-hunt: https://www.producthunt.com/@souravray
    twitter: /
    angellist : /
    linkedin: /
  post_count: 0
  highlight: kimbie

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
