nav:
  Home: /
  Résumé: /resume/
  Hire Me: /lets-work-together/

customize:
  gravatar:
    email: 123.sourav@gmail.com
  logo:
    enabled: true
    width: 64
    height: 64
    url: /images/logo.png
    gravatar: true
  favicon: 
    # eg. generate with http://realfavicongenerator.net/
  desktop:
    url: /images/favicon.ico
    gravatar: false
  android:
    url: /images/android-chrome-192x192.png
    gravator: false
  apple:
    url: /images/apple-touch-icon.png
    gravator: false
  social_links:
    github: http://github.com/souravray
    product-hunt: https://www.producthunt.com/@souravray
    twitter: https://twitter.com/souravray
    angellist : https://angel.co/souravray
    linkedin: https://www.linkedin.com/in/souravray/
  post_count: 0
  highlight: kimbie

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
